### PR TITLE
Fix HN changes in mid-April 2015

### PR DESCRIPTION
**Pull request by guiambros**
This new PR fixes the changes done to HN's DOM discussed on #6, as well as the changes published on April 15, 2015.

### CODE REVIEW

**Comment by goldfire** [comment]
Is this still working for you? It worked for me for a couple days, but hasn't worked at all since.

**Comment by guiambros** [comment]
@goldfire: yes, this is still working (as of 4/27), but this PR is still pending. Not sure @danmaz74 is still maintaining the project.

For the time being, I created a temporary fork at https://github.com/guiambros/HNMarkAllRead, and published the Chrome extension to http://j.mp/hnmarkread.

**Comment by goldfire** [comment]
Thanks, that is working now.

**Comment by danmaz74** [comment]
Hi guys!

Thanks for the pull request, I just merged it.

Unfortunately I really don't have time to maintain the project anymore, even if I had also some new ideas I wanted to add - I'm working on my struggling startup more than full time!

@guiambros would you like to take the helm? I can also share the app on the Chrome store. Just let me know if you'd like that :)

**Comment by guiambros** [comment]
@danmaz74, sure thing, would love to help. Can you add me to the github and to Chrome Store? I'll delete the clone temp extension I had created with the previous PR, and merge the code on the official one.

**Pull request merged**
